# Generated by Django 5.0.2 on 2024-02-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bufet_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcartitem',
            old_name='dish',
            new_name='item',
        ),
    ]
